### ISSUE TITLE
软件可以简单一点吧？

### ISSUE THREAD

**Issue by viponedream** [GoMinerProxy/GoMinerProxy#10]
一个可执行文件，一个配置文件。
然后可以复制到其它电脑直接运行。
现在弄得太复杂了。在一台电脑设置好了都没法复制到其它电脑过去。
里面各种加密都是多余的啊。
我们只要一个执行文件，一个简单的配置文件就行了啊。

**Comment by GoMinerProxy** [comment]
配置文件可以復製到其他伺服器使用
