### ISSUE TITLE
这个固定抽水比例 15G  的百分5  直接都跑到5G了

### ISSUE THREAD

**Issue by kfwblm** [GoMinerProxy/GoMinerProxy#6]
这个固定抽水比例 15G  的百分5  直接都跑到5G了

**Comment by GoMinerProxy** [comment]
因为不同矿池的难度不同，归集抽水到不同矿池的算力会有偏差，请根据实际进行调整或抽到同一矿池并选择随机算法

**Comment by kfwblm** [comment]
安装后打不开网页&nbsp; 在装个另外的抽水就好了。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GoMinerProxy/GoMinerProxy] 这个固定抽水比例 15G  的百分5  直接都跑到5G了 (Issue #6)





 
因為不同礦池的難度不同，歸集抽水到不同礦池的算力會有偏差，請根據實際進行調整或抽到同一礦池並選擇隨機算法。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
