### ISSUE TITLE
安装完成后打不开网页 装个别的抽水就可以打开网页- -

### ISSUE THREAD

**Issue by kfwblm** [GoMinerProxy/GoMinerProxy#7]
安装完成后打不开网页 装个别的抽水就可以打开网页- -

**Comment by GoMinerProxy** [comment]
提供一下後台輸出信息

**Comment by kfwblm** [comment]
有什么联系方式吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GoMinerProxy/GoMinerProxy] 安装完成后打不开网页 装个别的抽水就可以打开网页- - (Issue #7)





 
提供一下後台輸出信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kfwblm** [comment]
后台提示安装成功&nbsp; 但是网页打不开 我隔壁SU那个在安装下。。2个都正常打开- -




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GoMinerProxy/GoMinerProxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GoMinerProxy/GoMinerProxy] 安装完成后打不开网页 装个别的抽水就可以打开网页- - (Issue #7)





 
提供一下後台輸出信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GoMinerProxy** [comment]
<a href="https://t.me/+afVqEXnxtQAyNWNh">Telegram 討論群组</a>
